### PR TITLE
feat: 🍰 Header Logo Routing Update

### PR DESCRIPTION
**Pull request by adrianrojek**
## 🍰 Pullrequest
Updated the mobile screen header logo to route to external or internal URL according to change request from fork pull request.

### Issues

- fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5550
- related https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5572

### Todo
- [X] None

### CODE REVIEW

**Review by Tirokk — APPROVED** [review]
Hey @adrianrojek ,

this looks and works really good! 😍
Big thank for your help 🙏🏼

I justified a little the default for undefined `target` and set the default setting for the template network in `webapp/constants/logos.js`.
Hope that was okay?!

I approve! 🚀💫

You can merge if the test a successful.

**Comment by Tirokk** [comment]
Test are ready. @adrianrojek 
You can merge.

**Comment by adrianrojek** [comment]
Merged, thanks @Tirokk

**Comment by Tirokk** [comment]
My pleasure @adrianrojek 🍀💫

**Pull request merged**
