### PR TITLE
Fix console.errors during `yarn run test`

### PR DESCRIPTION
**Pull request by Tirokk**
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-07-30T19:13:51Z" title="Tuesday, July 30th 2019, 9:13:51 pm +02:00">Jul 30, 2019</time>_
_Merged <time datetime="2019-07-31T05:43:13Z" title="Wednesday, July 31st 2019, 7:43:13 am +02:00">Jul 31, 2019</time>_
---

@mattwr18 you added `currentUser` in 19b2b7a49 without running the tests,
didn't you?

### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
> [roschaefer](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-08-06T08:27:23Z" title="Tuesday, August 6th 2019, 10:27:23 am +02:00">Aug 6, 2019</time>_

---


Hi @Sydney-o9 thanks for this heads up about [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery)! I think you are correct that we don't have any particular CSRF protection in place. However I'm not quite sure how vulnerable we are to CSRF if we use JWT Bearer tokens. A quick research gave me [this](https://security.stackexchange.com/questions/170388/do-i-need-csrf-token-if-im-using-bearer-jwt) and [this](https://medium.com/node-security/cross-site-request-forgery-mitigation-for-express-js-apps-made-easy-using-the-same-site-cookie-flag-e19ee7d5b513). 

Maybe we could add some extra assurance by disallowing cookies in our backend like the thread opener of the first link suggested. :thinking:

I think it would help me and others if you could outline an example how a CSRF attack could look like in our case? Feel free to use our staging environment: https://nitro-staging.human-connection.org/ it should always run the lastest `master` branch.

**Comment by Tirokk** [comment]
> [stale[bot]](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2019-11-19T20:10:09Z" title="Tuesday, November 19th 2019, 9:10:09 pm +01:00">Nov 19, 2019</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-12-12T07:43:28Z" title="Thursday, December 12th 2019, 8:43:28 am +01:00">Dec 12, 2019</time>_

---


@roschaefer @mattwr18 @ogerly @alina-beck @datenbrei 
What can and what should we do about this security problem?

@Sydney-o9 can you be a help with this?

**Comment by Tirokk** [comment]
> [datenbrei](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-12-13T10:10:39Z" title="Friday, December 13th 2019, 11:10:39 am +01:00">Dec 13, 2019</time>_

---


I had a look at it. There seem to be some solutions on a framework level, like JSON-Web-Tokens ( JWT )/Bearer Tokens. Maybe, we can make use of existing solutions? Are there?

**Comment by Tirokk** [comment]
> [stale[bot]](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-02-11T11:02:22Z" title="Tuesday, February 11th 2020, 12:02:22 pm +01:00">Feb 11, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-03-06T07:51:04Z" title="Friday, March 6th 2020, 8:51:04 am +01:00">Mar 6, 2020</time>_

---


Still for the future …

**Comment by Tirokk** [comment]
> [stale[bot]](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-05-05T10:58:13Z" title="Tuesday, May 5th 2020, 12:58:13 pm +02:00">May 5, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-05-07T11:02:40Z" title="Thursday, May 7th 2020, 1:02:40 pm +02:00">May 7, 2020</time>_

---


Still valid I think

**Comment by ulfgebhardt** [comment]
There are no new commits between base branch 'master' and head branch 'pr1141head'

**Pull request closed without merging**
