### PR TITLE
feat: 🍰 Show Password Component 

### PR DESCRIPTION
**Pull request by Brandon-G-Tripp**
## 🍰 Pullrequest

Pull request pulls out logic for the ShowPassword into a component for use in various password fields. 

### Issues
#4312 

### Todo
- [ ] Implement in Registration Slider

### CODE REVIEW

**Comment by Tirokk** [comment]
That looks really good @Brandon-G-Tripp ! 🍀👍🏼
Nice that you care for this again.

And I very much appreciate that you wrote a test for it.

I just see one little leftover from last time:
### 
Bildschirmfoto 2021-04-15 um 14 20 26

Not very important, but would be nice if you could care for this little double boarder to vanish …

PS: Just in case you are interested to write a Cypress end-to-end test. Pull down the newest master and have a look into the cypress folder. There are are as well some instructions how to run the tests.

**Comment by Tirokk** [comment]
That looks really good @Brandon-G-Tripp ! 🍀👍🏼
Nice that you care for this again.

And I very much appreciate that you wrote a test for it. 😍

I just see one little leftover from last time at the moment:

Bildschirmfoto 2021-04-15 um 14 20 26

Not very important, but would be nice if you could care for this little double boarder to vanish …

PS: Just in case you are interested to write a Cypress end-to-end test.
After @ulfgebhardt merges his Cypress PR https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/4338 pull down the newest master and have a look into the cypress folder. There are as well some instructions how to run the tests.

**Comment by Brandon-G-Tripp** [comment]
@Tirokk Thanks for the feedback. I will work to get that border taken care of and attempt to write a Cypress test. 

I am sorry I did fully understand where to get the email confirmation code from Neo4J to get to the enter password page on the registration slide. I ran the query you suggested and did not receive anything back.

**Comment by Tirokk** [comment]
Sorry that I gave you the wrong Cypher statement before. @Brandon-G-Tripp 
I mixed them up …

**Comment by Tirokk** [comment]
Hey @Brandon-G-Tripp !
How is it going?

**Comment by Brandon-G-Tripp** [comment]
@Tirokk I apologize I was out of country for a week and a half and didn't have internet. I should have it finished by the end of the week. I will let you know if I run into any issues with the cypress testing or implementing in the registration slider.

**Comment by ulfgebhardt** [comment]
This branch needs a rebase! @Brandon-G-Tripp 
This will then include the required tests. To resolve the `yarn.lock` conflict one can run `yarn install` again to let yarn itself resolve the conflict.

**Comment by Brandon-G-Tripp** [comment]
@ulfgebhardt Ok perfect I will rebase. I do not have yarn on my local machine. Is there another way to resolve the conflict or should I install it?

**Comment by ulfgebhardt** [comment]
Just do the rebase and if there is a problem i can fix it - no problems <3 ty @Brandon-G-Tripp

**Review by ulfgebhardt — APPROVED** [review]
LGTM

**Comment by Brandon-G-Tripp** [comment]
@ulfgebhardt thank you. Looking forward to the next one.

**Review by Tirokk — CHANGES_REQUESTED** [review]
# !!! I did a mistake !!!

Hey @Brandon-G-Tripp 🤗

I don’t know why, but I can't see any show password icons on registration `http://localhost:3000/registration` at `Create user account`.

I double checked that I’m on the correct branch. See pic below 👇🏼

Hope I do nothing wrong …
Please check once again your self. 🙏🏼

Bildschirmfoto 2021-05-18 um 20 59 31

**Review by Tirokk — APPROVED** [review]
Hey @Brandon-G-Tripp 🤗

Cool and well done, dear !!! 🚀🚀💫💫
Everything works well after I reseted my branch. 🍀

I’m very glad that you cared again for this important feature 🙏🏼

It goes forward with you great help.
So please merge! 😍

PS: The only thing what is not fixed is the double line on the left side, but I really can live with it. If you like you could create a new issue for this.

**Comment by Brandon-G-Tripp** [comment]
@Tirokk Thank you for the review. I am happy to be back working on the project. 

I will definitely make an issue for the little css. I had trouble fixing it as the ds-input workaround created it. I will try to resolve it in the future.

**Pull request merged**
