### PR TITLE
Added Support Link To Notification E-Mail Templates & formated the fi…

### PR DESCRIPTION
**Pull request by saikathalderr**
## 🍰 Pullrequest

Added Support Link To Notification E-Mail Templates & formatted the HTML files for more readability.

###  Feature
- #4794 

### Todo

- [X]  added the additional support link to the tests of the notification e-mail templates

### CODE REVIEW

**Comment by Tirokk** [comment]
Hey @saikathalderr ,

cool and really nice that you take over this issue. 😍

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

**One little Problem**

Please don’t compare from your fork to this repository, because the publish action will fail, because of permission problems with the credentials.

Create a new PR by just pushing your branch directly to this repo and compare to the master.
Close this issue.

If you accept the invitation then you’ll have the right todo so. 😉
And I will assign you to the issue and PR.

Cool? 🤗

**Comment by Tirokk** [comment]
The code looks good on the first glance. 👍🏼
I will test it after you created the new issue.

If you like to be really cool then test in `XXX` for this support link. 😉

**Comment by Tirokk** [comment]
I clarified my comments above @saikathalderr 👆🏼

**Comment by saikathalderr** [comment]
Yap! checking on it

**Comment by Tirokk** [comment]
Reopen to investigate GitHub functionality …

**Pull request closed without merging**
