### PR TITLE
Centered the login-form

### PR DESCRIPTION
**Pull request by somesh202**
## 🍰 Pullrequest
Centered the Login-form and created a separate class for registration-slider

### Issues

- #4481 

### Todo

- [X] None

### CODE REVIEW

**Review by Tirokk — APPROVED** [review]
Hey @somesh202 ,

YES! That looks really nice. 😍

Thanks a lot for contributing to ocelot.social !!!
And for your patience 🙏🏼

I approve your first piece to the big cake! 🚀💫

if the tests are successful you can merge your code yourself if you like!?

**Comment by somesh202** [comment]
> Hey @somesh202 ,
> 
> YES! That looks really nice. 😍
> 
> Thanks a lot for contributing to ocelot.social !!!
> And for your patience 🙏🏼
> 
> I approve your first piece to the big cake! 🚀💫
> 
> If the tests are successful you can merge your code yourself if you like!?
> 
> PS: The `lint webapp` test showed an error, because we have the linting check switched on.
> I allowed myself to fix the problem by running:
> 
> ```shell
> # in webapp folder
> $ yarn lint --fix
> ```
> 
> And I pushed the change to this PR. It was just a space to much at the end of a line.
> Just run this command on your local code if you changed something in the webapp or the backend before you push the code.

I haven't changed anything after pushing this, so do I need to run this command now?

**Comment by Tirokk** [comment]
> I haven't changed anything after pushing this, so do I need to run this command now?

You "should“ have run this command before you push the branch here. At least before your last push right before you demand a review. This is because otherwise the test can fail.

In this case I pulled this branch to my local machine, run this command, did the commit, and I pushed it back here so that there is nothing to do for you now:

My commit:
https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/4660/commits/e9189a3c58edd87edf3c71c52a5d025cfc4942a7

**Comment by Tirokk** [comment]
Luckily I’m not as perfect. ^^

The webapp test `pages/registration.spec.js` failed, because I forgot to rename the renamed class `registration-slider` there as well. I fixed it with an additional commit:
https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/4660/commits/198d24ecb195489aef32b9884f5950a4f28e8256

Locally one can check this by running:

```bash
# in webapp folder
$ yarn test
```

**Comment by Tirokk** [comment]
Now you can merge if you like? @somesh202 
👍🏼

**Comment by somesh202** [comment]
> Now you can merge if you like? @somesh202
> 👍🏼👇🏼

Sure! Thank you so much. I'll 

> > I haven't changed anything after pushing this, so do I need to run this command now?
> 
> I did it for you … 🤗
> 
> You "should“ have run this command before you push the branch here. At least before your last push right before you demand a review. This is because otherwise the test can fail.
> 
> In this case I pulled this branch to my local machine, run this command, did the commit, and I pushed it back here so that there is nothing to do for you now:
> 
> My commit: 👆🏼
> [e9189a3](https://github.com/Ocelot-Social-Community/Ocelot-Social/commit/e9189a3c58edd87edf3c71c52a5d025cfc4942a7)
> 
> PS: Unfortunately the tests are still a bit flaky. Therefore we have to rerun them in case they fail. See here: https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/4660/checks

Okay! I'll keep this in mind while contributing next time. Thanks !

**Pull request merged**
