### PR TITLE
fix: [wip] migrate legacy embed markup [3395]

### PR DESCRIPTION
**Pull request by Tirokk**
> [rbeer](https://github.com/rbeer) **Authored by [rbeer](https://github.com/rbeer)**
_<time datetime="2020-04-12T23:52:55Z" title="Monday, April 13th 2020, 1:52:55 am +02:00">Apr 13, 2020</time>_

---

## 🍰 Pullrequest
Adds migrattion to update posts with embeds to new block level style markup; the transformation ensures paragraphs around embeds.

```html
<p><a href=\"https://youtu.be/jB6mI8uVxKU\" class=\"embed\" target=\"_blank\"></a></p>
```
to
```html
<p></p><a href=\"https://youtu.be/jB6mI8uVxKU\" class=\"embed\" target=\"_blank\"></a><p></p>
```

### Issues
- fixes [2] of #3395

### Todo
 - [ ] Write migration

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-04-12T23:56:04Z" title="Monday, April 13th 2020, 1:56:04 am +02:00">Apr 13, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7043/specs"></a> <b title="Passed">65</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7043/failures"></a> <b title="Failed">1</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Failed |
| **Commit** | bff91b0e45 |
| **Started** | Apr 16, 2020 1:45 PM |
| **Ended** | Apr 16, 2020 2:06 PM |
| **Duration** | 20:17 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7043/specs)


---

### Failures

<table>
  <tbody>
    <tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          cypress/integration/notifications/Mentions.feature <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7043/failures">⏯</a>
        </th>
        <th align="right">
          1&nbsp;<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7043/failures">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7043/failures/4beb6f80-8ba6-47a4-bed9-737ca12ddb05">
            Notification for a mention > Mention another user, re-login as this user and see notifications</td>
          </a>
          <td>
            <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7043/failures/4beb6f80-8ba6-47a4-bed9-737ca12ddb05">
              
            </a>
                </td>
      </tr>
  </tbody>
</table>


---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-04-13T00:40:07Z" title="Monday, April 13th 2020, 2:40:07 am +02:00">Apr 13, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7042/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7042/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 816e58fd25 <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Apr 16, 2020 1:45 PM |
| **Ended** | Apr 16, 2020 2:05 PM |
| **Duration** | 19:29 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7042/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [stale[bot]](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-06-15T17:28:19Z" title="Monday, June 15th 2020, 7:28:19 pm +02:00">Jun 15, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by ulfgebhardt** [comment]
@Tirokk is this still valid?

**Comment by Tirokk** [comment]
Probably it’s not necessary anymore, but that needs further investigation on the related issue I guess.

**Pull request closed without merging**
