### PR TITLE
feat: 🍰 Add Group To User Teaser, On Post Page, And On News Feed Etc.

### LINKED ISSUE #5501: 🚀 [Feature] Add Group Link And Slug To Post Teasers And Post Page
## :rocket: Feature Request

Add group link and slug to post teasers and post page.

### PR DESCRIPTION
**Pull request by Tirokk**
## 🍰 Pull Request

Add group link to user teaser on posts in webapp.

### Issues

fixes #5501
relates #5059 

### Todo

- [x] none

### CODE REVIEW

**Review by Mogge — CHANGES_REQUESTED** [review]
Code looks good to me.
 * On the user profile, the group is not shown on the post teaser
 * In the group profile, the group is not shown on the post teaser

Is this on purpose?

**Comment by Tirokk** [comment]
> Code looks good to me.
> 
>     * On the user profile, the group is not shown on the post teaser
> 
>     * In the group profile, the group is not shown on the post teaser
> 
> 
> Is this on purpose?

This was not on porpose and I have solved this. @Mogge

**Review by ulfgebhardt — CHANGES_REQUESTED** [review]
In the group profile there is still an `@` in the profile 
image

**Review by ulfgebhardt — DISMISSED** [review]
image

There should be an `in` between user and the group
`@jenny-rostock Jenny Rostock in &school-for-citizens School For Citizens`

**Review by ulfgebhardt — APPROVED** [review]

**Pull request merged**
