### PR TITLE
fix: [WIP] 🍰 Editor List Styles [3492]

### LINKED ISSUE #3492: 🐛 [Bug] Lists in posts and comments are not displayed as lists
> [sushidave](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-04-20T19:25:09Z" title="Monday, April 20th 2020, 9:25:09 pm +02:00">Apr 20, 2020</time>_

---

## :bug: Bugreport

Since release 0.6.0 numbered and unordered lists in posts and comments are no longer displayed as lists anymore, nor in the editor.

hc-bug-3492-screenshot

### Steps to reproduce the behavior
1. Create a new post or a comment.
2. Format any text by clicking one of the list buttons of the toolbar.
3. The list is not displayed as a list.
4. Save the post or comment => the list is not displayed as a list.

### Expected behavior

The lists are displayed as lists.

### Version & Environment
 Type: [Notebook]      
 - OS: [macOS]      
 - Browser: [Firefox] 
 - Version [75.0]  
 - Device: [MacBook]  

### Additional context

Checked with @mattwr18

### PR DESCRIPTION
**Pull request by Tirokk**
> [rbeer](https://github.com/rbeer) **Authored by [rbeer](https://github.com/rbeer)**
_<time datetime="2020-04-21T00:20:09Z" title="Tuesday, April 21st 2020, 2:20:09 am +02:00">Apr 21, 2020</time>_

---

## 🍰 Pullrequest
Adds decorators back to `<ul>`, `<ol>` Elements, inside Editor.
Using the logo as bullet is maybe a bit over the top :relaxed: 

list_decorators

list_decorators_content

### Issues
- fixes #3492

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-04-21T02:22:44Z" title="Tuesday, April 21st 2020, 4:22:44 am +02:00">Apr 21, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7070/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7070/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 408b939c40 <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Apr 21, 2020 2:54 AM |
| **Ended** | Apr 21, 2020 3:16 AM |
| **Duration** | 21:42 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7070/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-04-21T02:29:26Z" title="Tuesday, April 21st 2020, 4:29:26 am +02:00">Apr 21, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7076/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7076/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | a8ec2f53ed |
| **Started** | Apr 21, 2020 1:12 PM |
| **Ended** | Apr 21, 2020 1:36 PM |
| **Duration** | 23:42 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7076/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-05-27T11:59:32Z" title="Wednesday, May 27th 2020, 1:59:32 pm +02:00">May 27, 2020</time>_

---


Hey @rbeer ,
do you have time to care for this issue or PR? 🤗💫
Greetings

**Comment by Tirokk** [comment]
> [sushidave](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-08-05T10:06:08Z" title="Wednesday, August 5th 2020, 12:06:08 pm +02:00">Aug 5, 2020</time>_

---


@rbeer @Tirokk Great if this could be impemented by the next release together with the PR for the margin issue #3628. 
@rbeer If you don't have time for this now we could ask the contributor of the margin issue to take over. Please advise.

**Review by Mogge — CHANGES_REQUESTED** [review]
Hey @rbeer ,

great that you care for this. Very important! 💫

The code looks good and nice as far I can see.

About the functionality I have stated some comments in the both following pictures:

Bildschirmfoto 2020-04-23 um 14 39 11

Bildschirmfoto 2020-04-23 um 14 48 37

Only just in case you could do something about it … 🤗🙏🏼

**Pull request closed without merging**
