### PR TITLE
refactor: set up/clear database only once [3468]

### LINKED ISSUE #3468: 🔧 [Refactor] backend test db setups/teardowns
> [rbeer](https://github.com/rbeer) **Authored by [rbeer](https://github.com/rbeer)**
_<time datetime="2020-04-12T22:46:15Z" title="Monday, April 13th 2020, 12:46:15 am +02:00">Apr 13, 2020</time>_

---

## :zap: Refactor ticket
Backend tests are slow, because the test DB is often cleared after each test of a suite.
Seting up the database only once before and clearing it only after each suite reduces the test time by e.g. 60%.

beforeEach
beforeAll

### Motive
travis_runtime

### Implementation
- fix `before|afterAll`, `before|afterEach` blocks in tests

### See also
For time logs of the `before|afterAll` block executions, see this [Travis log](https://travis-ci.com/github/Human-Connection/Human-Connection/builds/159993119#L1435)

### PR DESCRIPTION
**Pull request by Tirokk**
> [rbeer](https://github.com/rbeer) **Authored by [rbeer](https://github.com/rbeer)**
_<time datetime="2020-04-12T23:02:49Z" title="Monday, April 13th 2020, 1:02:49 am +02:00">Apr 13, 2020</time>_

---

## 🍰 Pullrequest
Reduces backend testing time by lowering the amount of database recreations.

### Issues
- fixes #3468

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-04-12T23:38:09Z" title="Monday, April 13th 2020, 1:38:09 am +02:00">Apr 13, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/6977/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/6977/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 2731a25193 |
| **Started** | Apr 12, 2020 11:15 PM |
| **Ended** | Apr 12, 2020 11:38 PM |
| **Duration** | 22:29 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/6977/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-04-12T23:44:19Z" title="Monday, April 13th 2020, 1:44:19 am +02:00">Apr 13, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/6978/specs"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/6978/failures"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | f5109b8144 <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Apr 12, 2020 11:22 PM |
| **Ended** | Apr 12, 2020 11:44 PM |
| **Duration** | 21:39 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/6978/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

**Comment by Tirokk** [comment]
> [rbeer](https://github.com/rbeer) **Authored by [rbeer](https://github.com/rbeer)**
_<time datetime="2020-04-23T11:49:16Z" title="Thursday, April 23rd 2020, 1:49:16 pm +02:00">Apr 23, 2020</time>_

---


As discussed in today's stand-up, I will put this on hold for now.
While this would be an awesome quality of life improvement, it's not critical, yet should be thoroughly planned - done in parent issue.

**Comment by Tirokk** [comment]
> [stale[bot]](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-06-22T11:52:16Z" title="Monday, June 22nd 2020, 1:52:16 pm +02:00">Jun 22, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
May @mogge and I can find time somewhen to care for this …

**Comment by ulfgebhardt** [comment]
@Mogge can you review this? <3

**Comment by ulfgebhardt** [comment]
Closing: very old content, minor changes, conflicts - it goes!

**Pull request closed without merging**
