### PR TITLE
refactor : removed EnterNonce.vue

### LINKED ISSUE #5035: 🔧 [Refactor] EnterNonce.vue Seems Unused And Should Be Removed
## 🔧 Refactor

`webapp/components/EnterNonce/EnterNonce.vue` seems to be unused and should be removed.

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
### Issues
- Fixes #5035 

### Todo

- [X] None

### CODE REVIEW

**Comment by Tirokk** [comment]
Hey @PrajwalBorkar ,

yes for sure you can take over. That’s great! 🤗
I assigned you to this issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

Please don’t compare from your fork to this repository, in case, because the publish action will fail, because of permission problems with the credentials.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉

PS: You compared from your fork and usualy this does not work, see above. If the test erroring out, please push directly to our repo and open a new PR for it …

**Comment by Tirokk** [comment]
Thanks for contributiong to ocelot.social !!! 🙏🏼

**Comment by Tirokk** [comment]
It looks like the tests are not starting.
Please follow the suggestions above by accept our invitation and pushing directly to out repo. 🙏🏼

**Comment by PrajwalBorkar** [comment]
Im not able to push to repo. Can u explain?
Screenshot (79)

**Comment by Tirokk** [comment]
In the case of your screen shot it seems the content of your branch is exactly the same as the `master` branch.
Then GitHub states that there is nothing to compare, because it's just the same.

That means in the branch you pushed there's the file `webapp/components/EnterNonce/EnterNonce.vue` not delted like in the branch of your fork in this PR we are writing on.
Can that be true? @PrajwalBorkar 

So first delete the file localy in your branch, then push again directly to our repo, and then compare again and create a new PR with it …

**Comment by PrajwalBorkar** [comment]
https://github.com/PrajwalBorkar/Ocelot-Social/pull/1 check this and please review for any changes

**Comment by PrajwalBorkar** [comment]
Review for any changes https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5214

**Pull request closed without merging**
