### PR TITLE
feat: New Model Implementation

### PR DESCRIPTION
**Pull request by Tirokk**
> [araujoheiker](https://github.com/araujoheiker) **Authored by [araujoheiker](https://github.com/araujoheiker)**
_<time datetime="2020-08-26T15:44:51Z" title="Wednesday, August 26th 2020, 5:44:51 pm +02:00">Aug 26, 2020</time>_

---

## 🍰 Pullrequest
Initial Changes.

### CODE REVIEW

**Comment by Tirokk** [comment]
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-08-27T09:54:58Z" title="Thursday, August 27th 2020, 11:54:58 am +02:00">Aug 27, 2020</time>_

---


Hello @araujoheiker 
This looks very interesting what you have done. I am actually working on another implementation of organizations (see https://github.com/Human-Connection/Human-Connection/tree/organizations). Can we meet to discuss your thoughts?

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-08-27T17:09:15Z" title="Thursday, August 27th 2020, 7:09:15 pm +02:00">Aug 27, 2020</time>_

---


Hello @araujoheiker ,

I cared for your invitation to our repository as volunteer via an e-mail invitation you can accept.
After you accept, please clone this repo (don’t fork) **push your feature branch directly to this repo and create a PR using master** as the base branch.
(Pushing from your fork is the reason for the Travis Error … 👇🏼)

I assigned you to this issue …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to there:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.

PS: I and we will be not available till Monday.

**Comment by Mogge** [comment]
This PR is in conflict with  #3735. I suggest to close it.

**Comment by Tirokk** [comment]
It’s a pity that @araujoheiker spend so much effort and we have to close it.
But I don’t know what to do either with it but closing. @Mogge 

Sorry!

**Pull request closed without merging**
