### PR TITLE
fix: 🍰 Suggestion List Filter

### LINKED ISSUE #2635: 🐛 [Bug] Some users with short usernames missing on mention menu and cannot be mentioned
> [sushidave](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2019-12-30T20:56:53Z" title="Monday, December 30th 2019, 9:56:53 pm +01:00">Dec 30, 2019</time>_

---

## :bug: Bugreport

Some users with a short username are missing on mention menu. Consequently, they can't be mentioned in a post or comment. Example: Username "tj" (@tj)

### Steps to reproduce the behavior
1. Create a post or a comment
2. Type the "at" sign (@) and the letters "tj".
3. Username tj is missing on the mention menu. The number of usernames on the menu is limited.
4. User cannot be mentioned.
5. Abort process

### Expected behavior

Username should be visible and selectable.

### Version & Environment
 - Type: [Desktop]      
 - OS: [macOS]      
 - Browser: [Firefox] 
 - Version [71.0]  
 - Device: [MacBook]

### PR DESCRIPTION
**Pull request by ashleysylvialee**
## 🍰 Pullrequest
- Changed suggestion list filtering to search for prefix instead of substring
- Sorted results by length so stricter matches show up on top
image
- Added spacebar selection functionality for mentions

### Issues
- Fixes #2635 

### Todo
- None

### CODE REVIEW

**Review by Tirokk — CHANGES_REQUESTED** [review]
Hey @ashleysylvialee !

That looks really nice and well done !!! 🚀💫
An easy and good solution 🍀
Thanks for your contribution! 🙏🏼

I like to approve 👍🏼
… if the tests will run, what has nothing to do with your changes @ashleysylvialee .

Just in case you are interested on:
Would be cool if you could add a test for this in `webapp/components/Editor/Editor.spec.js`.

@mogge may you have a look at failing the tests in the backend?

**Comment by Tirokk** [comment]
I have a little additional functionally suggestion, if you are interested:

Bildschirmfoto 2021-03-16 um 10 41 04

I would await that if I type a fitting slug, see ☝🏼, and hit the space key that the selected menu item will be chosen.

There is a similar example for hashtags already in the code @ashleysylvialee :

https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/b1dec55449521349c1337eced78e9079172f5bc1/webapp/components/Editor/Editor.vue#L184-L188

Just in case you are interested … 😍

**Comment by Mogge** [comment]
I fixed the failing tests. Feel free to merge, although I like the suggestion @Tirokk brought up

**Review by Tirokk — APPROVED** [review]

**Comment by ashleysylvialee** [comment]
> I have a little additional functionally suggestion, if you are interested:
> 
> Bildschirmfoto 2021-03-16 um 10 41 04
> 
> I would await that if I type a fitting slug, see ☝🏼, and hit the space key that the selected menu item will be chosen.
> 
> There is a similar example for hashtags already in the code @ashleysylvialee :
> 
> https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/b1dec55449521349c1337eced78e9079172f5bc1/webapp/components/Editor/Editor.vue#L184-L188
> 
> Just in case you are interested … 😍

Done! The tests I wrote are passing as well. 🥳 Anything else you'd like me to add here? 😊

**Review by Tirokk — APPROVED** [review]
Hey @ashleysylvialee .
Really cool job you’ve done!!!
Our users will be happy about your work and effort you spend. 🚀🚀💫💫

Great to have you in the project.

So I just fixed the linting: `yarn lint --fix`
And I approve.
Please merge!

PS: In case you change the locales they should be checked as well by : `yarn locales --fix`

Precisley how I like it

**Pull request merged**
