### PR TITLE
feat(webapp): [WIP] add event detail page

### PR DESCRIPTION
**Pull request by maeckes-infinitylabs**
## 🍰 Pullrequest

Adds an event route with event detail page as endpoint.

### Issues

- relates #6045 

### Todo

- [x] Add Event Details to PostDetail Component
- [ ] Add Map View for event location to PostDetail Component
- [ ] Translate new strings

### CODE REVIEW

**Comment by Mogge** [comment]
@maeckes-infinitylabs I did rebase this PR on the `event-master` branch. I suggest, you work on this branch as base, to have the backend available for events.
I suggest a different approach: Do not create a event page. We use the same page for events and articles. Inside the post page, you check, if `postType === 'Event'` and render the `EventDetails` if true.

**Comment by Mogge** [comment]
These are the new properties for posts you can expect from the backend:
```
  postType: [PostType]
    @cypher(statement: "RETURN filter(l IN labels(this) WHERE NOT l = 'Post')")

  eventLocationName: String
  eventLocation: Location @cypher(statement: "MATCH (this)-[:IS_IN]->(l:Location) RETURN l")
  eventVenue: String
  eventStart: String
  eventEnd: String
  eventIsOnline: Boolean
```

**Comment by Mogge** [comment]
```
enum PostType {
  Article
  Event
}
```

**Review by Elweyn — CHANGES_REQUESTED** [review]
See @Mogge comments

**Comment by maeckes-infinitylabs** [comment]
> I did rebase this PR on the event-master branch. I suggest, you work on this branch as base, to have the backend available for events.

Thanks for the advice, will do.

> I suggest a different approach: Do not create a event page. We use the same page for events and articles. Inside the post page, you check, if postType === 'Event' and render the EventDetails if true.

I had the same idea but also added an event route:
- i created a postdetail vue component, that i added to the post route and also to the event route
- in the component itself i look which type it is and show details accordingly 

@Mogge 
i thought it would be good to have a specific event route. 
so should i revert this and just edit the post page and add not event route?

**Comment by maeckes-infinitylabs** [comment]
> See @Mogge comments

thanks for the hint. just missed it :sweat:

**Pull request closed without merging**
