### PR TITLE
feat: [WIP] 🍰 Basic Organisations

### PR DESCRIPTION
**Pull request by Tirokk**
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-07-22T10:45:53Z" title="Wednesday, July 22nd 2020, 12:45:53 pm +02:00">Jul 22, 2020</time>_

---

## 🍰 Pullrequest
First approach to implement organizations.
 * Add organization button in AvatarMenu

### Issues
- relates #281

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-07-22T11:27:02Z" title="Wednesday, July 22nd 2020, 1:27:02 pm +02:00">Jul 22, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8025/specs?utm_source=github"></a> <b title="Passed">65</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8025/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D"></a> <b title="Failed">1</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Failed |
| **Commit** | 1004e030b0 |
| **Started** | Sep 30, 2020 12:29 PM |
| **Ended** | Sep 30, 2020 12:54 PM |
| **Duration** | 25:11 <a href="https://on.cypress.io/parallelization?utm_source=github" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/8025/specs?utm_source=github)


---

### Failures

<table>
  <tbody>
    <tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          cypress/integration/user_profile/AboutMeAndLocation.feature <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8025/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">⏯</a>
        </th>
        <th align="right">
          1&nbsp;<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8025/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8025/test-results/3db5a8f4-814d-40ff-bd84-14395c2482d7?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
            About me and location > I set my location to "Saxony-Anhalt" (example #2)</td>
          </a>
          <td>
            <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8025/test-results/3db5a8f4-814d-40ff-bd84-14395c2482d7/screenshots?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
              
            </a>
                </td>
      </tr>
  </tbody>
</table>


---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings?utm_source=github)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-07-22T11:30:54Z" title="Wednesday, July 22nd 2020, 1:30:54 pm +02:00">Jul 22, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/specs?utm_source=github"></a> <b title="Passed">61</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D"></a> <b title="Failed">4</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">1</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Failed |
| **Commit** | 6f7d8ab0fc <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Sep 30, 2020 12:28 PM |
| **Ended** | Sep 30, 2020 12:54 PM |
| **Duration** | 25:09 <a href="https://on.cypress.io/parallelization?utm_source=github" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/8024/specs?utm_source=github)


---

### Failures

<table>
  <tbody>
    <tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          administration/TagsAndCategories.feature <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">⏯</a>
        </th>
        <th align="right">
          1&nbsp;<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results/4f5b56a6-d2ad-482c-b4fd-564479a96cd2?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
            Tags and Categories > See an overview of categories</td>
          </a>
          <td>
            <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results/4f5b56a6-d2ad-482c-b4fd-564479a96cd2/screenshots?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
              
            </a>
                </td>
      </tr><tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          notifications/Mentions.feature <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">⏯</a>
        </th>
        <th align="right">
          1&nbsp;<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results/598dc9cf-4786-497a-a297-bff84594af0e?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
            Notification for a mention > Mention another user, re-login as this user and see notifications</td>
          </a>
          <td>
            <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results/598dc9cf-4786-497a-a297-bff84594af0e/screenshots?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
              
            </a>
                </td>
      </tr><tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          user_account/ChangePassword.feature <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">⏯</a>
        </th>
        <th align="right">
          1&nbsp;<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results/e5c5edc2-d06f-4b50-acfa-2ced4fa518ad?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
            Change password > Change my password</td>
          </a>
          <td>
            <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results/e5c5edc2-d06f-4b50-acfa-2ced4fa518ad/screenshots?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
              
            </a>
                </td>
      </tr><tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          user_profile/AboutMeAndLocation.feature <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">⏯</a>
        </th>
        <th align="right">
          1&nbsp;<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results/a45fdafc-b076-49d5-83b6-7babdbb8c95b?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
            About me and location > I set my location to "Paris" (example #1)</td>
          </a>
          <td>
            <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8024/test-results/a45fdafc-b076-49d5-83b6-7babdbb8c95b/screenshots?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
              
            </a>
                </td>
      </tr>
  </tbody>
</table>


---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings?utm_source=github)

**Comment by Tirokk** [comment]
> [ogerly](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2020-08-21T07:00:26Z" title="Friday, August 21st 2020, 9:00:26 am +02:00">Aug 21, 2020</time>_

---


I have created the style as visible on the picture
FireShot Capture 349 - Human Connection - Human Connection - localhost

**Comment by Tirokk** [comment]
> [Lulalaby](https://github.com/Lulalaby) **Authored by [Lulalaby](https://github.com/Lulalaby)**
_<time datetime="2020-09-30T10:27:34Z" title="Wednesday, September 30th 2020, 12:27:34 pm +02:00">Sep 30, 2020</time>_

---


Something new already?

**Comment by ulfgebhardt** [comment]
Can we throw this away @Mogge @Tirokk ?

**Pull request closed without merging**
