### PR TITLE
feat: Export User Data

### PR DESCRIPTION
**Pull request by Tirokk**
> [Mogge](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-09-24T15:30:04Z" title="Thursday, September 24th 2020, 5:30:04 pm +02:00">Sep 24, 2020</time>_

---

## 🍰 Pullrequest
The users can download a Json with their profile data, all the posts they have written, and all the posts they have commented.

### Issues
- #3863

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-09-24T16:12:37Z" title="Thursday, September 24th 2020, 6:12:37 pm +02:00">Sep 24, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8020/specs?utm_source=github"></a> <b title="Passed">65</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8020/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D"></a> <b title="Failed">1</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Failed |
| **Commit** | 9b2bf64db5 |
| **Started** | Sep 30, 2020 9:43 AM |
| **Ended** | Sep 30, 2020 10:08 AM |
| **Duration** | 25:27 <a href="https://on.cypress.io/parallelization?utm_source=github" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/8020/specs?utm_source=github)


---

### Failures

<table>
  <tbody>
    <tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          cypress/integration/user_profile/AboutMeAndLocation.feature <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8020/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">⏯</a>
        </th>
        <th align="right">
          1&nbsp;<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8020/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8020/test-results/e83ad655-c29a-4908-a9a0-b32f3abf16d1?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
            About me and location > I set my location to "Paris" (example #1)</td>
          </a>
          <td>
            <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/8020/test-results/e83ad655-c29a-4908-a9a0-b32f3abf16d1/screenshots?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
              
            </a>
                </td>
      </tr>
  </tbody>
</table>


---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings?utm_source=github)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-09-24T16:15:42Z" title="Thursday, September 24th 2020, 6:15:42 pm +02:00">Sep 24, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7995/specs?utm_source=github"></a> <b title="Passed">65</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7995/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D"></a> <b title="Failed">1</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Failed |
| **Commit** | 4989721510 <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Sep 24, 2020 3:50 PM |
| **Ended** | Sep 24, 2020 4:15 PM |
| **Duration** | 25:01 <a href="https://on.cypress.io/parallelization?utm_source=github" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 78  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7995/specs?utm_source=github)


---

### Failures

<table>
  <tbody>
    <tr>
        <th align="center">
          
        </th>
        <th align="left" colspan="2" style="width: 100%">
          cypress/integration/user_profile/AboutMeAndLocation.feature <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7995/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">⏯</a>
        </th>
        <th align="right">
          1&nbsp;<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7995/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">Failed</a>
        </th>
      </tr><tr>
        <td align="right">1</td>
        <td colspan="2">
          <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7995/test-results/abe7dfd9-479c-4b97-a31e-5e0e0affb3a1?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
            About me and location > I set my location to "Paris" (example #1)</td>
          </a>
          <td>
            <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7995/test-results/abe7dfd9-479c-4b97-a31e-5e0e0affb3a1/screenshots?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D">
              
            </a>
                </td>
      </tr>
  </tbody>
</table>


---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings?utm_source=github)

**Review by Mogge — APPROVED** [review]

**Comment by Mogge** [comment]
This is outdated. There is a much better version in the HC repository. I will try to recover that.

**Comment by Tirokk** [comment]
Cool @Mogge 😍

**Pull request merged**
