### PR TITLE
fix: 🍰 Sign Up Page On Safari

### LINKED ISSUE #3788: 🐛 Sign Up Page is Broken
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-08-10T07:48:16Z" title="Monday, August 10th 2020, 9:48:16 am +02:00">Aug 10, 2020</time>_
_Closed <time datetime="2020-09-23T10:17:52Z" title="Wednesday, September 23rd 2020, 12:17:52 pm +02:00">Sep 23, 2020</time>_
---

## :bug: Bugreport

@appinteractive reported me that the sign up page is broken.

### Steps to reproduce the behaviour

1. go on our social network
2. don’t log in
3. click on sign up
4. here you see

Bildschirmfoto 2020-08-10 um 09 40 38

### Expected behavior

I expect the page to be designed well.

I guess the logo is much to big.
See log in page …

### Version & Environment

Every

### Additional context

None

### PR DESCRIPTION
**Pull request by Tirokk**
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-09-17T08:42:50Z" title="Thursday, September 17th 2020, 10:42:50 am +02:00">Sep 17, 2020</time>_
_Merged <time datetime="2020-09-23T10:17:52Z" title="Wednesday, September 23rd 2020, 12:17:52 pm +02:00">Sep 23, 2020</time>_
---

## 🍰 Pullrequest

The SVG image has not the appropriate size on macOS Safari.

### Issues

- fixes #3788 

### Todo

- [X] Added 'width' and 'height' properties in the SVG 'webapp/static/img/sign-up/nicetomeetyou.svg'.
- Have found that these are present on other SVGs. For example 'webapp/static/img/sign-up/humanconnection.svg'.
- Couldn't find an other way …

### CODE REVIEW

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-09-17T09:20:44Z" title="Thursday, September 17th 2020, 11:20:44 am +02:00">Sep 17, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7957/specs?utm_source=github"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7957/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | ae8c4d7588 |
| **Started** | Sep 18, 2020 10:33 AM |
| **Ended** | Sep 18, 2020 10:56 AM |
| **Duration** | 23:00 <a href="https://on.cypress.io/parallelization?utm_source=github" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7957/specs?utm_source=github)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings?utm_source=github)

**Comment by Tirokk** [comment]
> [cypress[bot]](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-09-17T09:25:14Z" title="Thursday, September 17th 2020, 11:25:14 am +02:00">Sep 17, 2020</time>_

---



<p align="center">
  <br />
  
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7958/specs?utm_source=github"></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/7958/test-results?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D"></a> <b title="Failed">0</b>  &bull;  <b title="Pending">0</b> &bull;  <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 3c28261f4a <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Sep 18, 2020 10:33 AM |
| **Ended** | Sep 18, 2020 10:57 AM |
| **Duration** | 23:41 <a href="https://on.cypress.io/parallelization?utm_source=github" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68  |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/7958/specs?utm_source=github)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings?utm_source=github)

**Comment by Tirokk** [comment]
> [Tirokk](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-09-18T15:42:45Z" title="Friday, September 18th 2020, 5:42:45 pm +02:00">Sep 18, 2020</time>_

---


If you like @appinteractive you can have look if the sign in page is now correct. 🤗

**Review by Mogge — APPROVED** [review]

**Comment by appinteractive** [comment]
@Tirokk did not change anything for me, at least not in the live version but maybe it was mit deployed. 

As a rule of law thumb, you should specify dimensions in svgs by „viewBox“ instead of width and height.

**Comment by Tirokk** [comment]
Hey @appinteractive ! 🤗

For me it looks good now.
https://human-connection.social/registration/signup

I deployed it on production on Monday.

**Comment by appinteractive** [comment]
Hey @Tirokk still very big but better then before. image

**Comment by Tirokk** [comment]
Okay @appinteractive I see.

You mean on iOS mobil?!

But macOS Safari is working for you now?

**Comment by appinteractive** [comment]
Yes iOS but I think it effects all mobile browsers when the size is fixed.

**Comment by Tirokk** [comment]
Okidoki. @appinteractive 
I will create a different issue … 👍🏼

**Comment by Tirokk** [comment]
Created a new issue #3924 …

**Pull request closed without merging**
